### ISSUE TITLE
rm is not recognized as an internal command when runnig project

### ISSUE THREAD

**Issue by JamDev0** [nmn/nextjs-app-dir-stylex#1]
I just cloned the repo and installed the dependencies, but when i tryed to run the project it throws "is not recognized as an internal command"

The following screenshot shows me running `npm i` and then trying to run `npm run dev`
![Screenshot_158](https://github.com/nmn/nextjs-app-dir-stylex/assets/61752887/f463ae90-e530-448e-9fde-60e83b966869)

**Comment by nmn** [comment]
I understand the problem. `rm -rf` is a *nix command that only works on macOS or Linux.

Could you try replacing `rm -rf .next` in the package.json with `rmdir /s /q .next` and see if that solves the problem for you?

**Comment by JamDev0** [comment]
I needed to do like so `if exist .next rmdir /s /q .next` as rmdir throws an error when the repo dosen't exists. But it worked, thanks :]
