### ISSUE TITLE
createVars does not exists in styleX

### ISSUE THREAD

**Issue by JamDev0** [nmn/nextjs-app-dir-stylex#3]
I could not find where else to create this issue, and i saw that you are one of the maintainers, so i thought you could help.

I was trying to create some variables to use on my project, but when i call the method createVars of styleX it throws Property 'createVars' does not exist on type 'IStyleX'.
![Screenshot_161](https://github.com/nmn/nextjs-app-dir-stylex/assets/61752887/83f6409d-693d-4d92-95ed-a0e23be177f0)

I notice that the styleX object has an unstable_createVars, I am supposed to use that instead of the createVars that the docs suggests?

**Comment by clintandrewhall** [comment]
Given that the code in this repo [uses](https://github.com/nmn/nextjs-app-dir-stylex/blob/main/app/globalTokens.stylex.ts#L75)  `unstable_createVars`, it's a fair bet that's what should be used for now.
